version: '3.8'

services:
  lab:
    container_name: lab-php
    image: manhdev2002/kma-lab:latest
    ports:
      - 3000:80
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=zIbHa*hLJBMK@wt9
    ports:
      - '5432:5432'
    volumes: 
      - .docker/db:/var/lib/postgresql/data

volumes:
  db:
    